In [1]:
import catastro as cat

parcel_name = 'Agroval'

gdf = cat.open_data(r"C:\Users\dani\OneDrive - Weif Agrotecnia SL\1_Equipo_WEITEC\08_PROYECTOS\01_PLATAFORMA_SaaS_AGTech\05_Geodata\25_10_03 Parcel_database.xlsx")
gdf = gdf[gdf['field'] == parcel_name]
main_gdf, error_df = cat.polygonize_data_parallel(gdf)
main_gdf

ENVIRONMENT set to -> dev
Prov: 46 || Mun: 176 || Pol: 14 || Par: 1 Rec: 11.0Prov: 46 || Mun: 176 || Pol: 14 || Par: 1 Rec: 4.0 Found: 1 plots
 Found: 1 plots
Prov: 46 || Mun: 176 || Pol: 14 || Par: 1 Rec: 1.0 Found: 1 plots
Prov: 46 || Mun: 253 || Pol: 9 || Par: 247 Rec: 10.0 Found: 1 plots
Prov: 46 || Mun: 253 || Pol: 9 || Par: 247 Rec: 14.0 Found: 1 plots
DONE!
Fields detected:  1 ['Agroval']
Total: 5 plots
Errors:  0

,geometry,provincia,municipio,agregado,zona,poligono,parcela,recinto,dn_surface,pendiente_media,coef_regadio,admisibilidad,incidencias,uso_sigpac,region,altitud,field,client,crop,operating
0,"POLYGON ((-0.65486 38.91992, -0.65491 38.92001...",46,176,0,0,14,1,1,91187.0,5.1,100,None,"74,75",CI,12,255,Agroval,SMT,Cítricos,False
0,"POLYGON ((-0.65367 38.92137, -0.65372 38.92139...",46,176,0,0,14,1,11,3307.0,4.8,100,None,"220,74",CI,6,253,Agroval,SMT,Cítricos,False
0,"POLYGON ((-0.65277 38.91852, -0.65283 38.91859...",46,176,0,0,14,1,4,320.0,10.7,100,None,"199,75",FY,12,239,Agroval,SMT,Cítricos,False
0,"POLYGON ((-0.65658 38.9197, -0.65664 38.91973,...",46,253,0,0,9,247,14,23355.0,4.0,100,None,"74,75",CI,12,251,Agroval,SMT,Cítricos,False
0,"POLYGON ((-0.66002 38.91788, -0.6609 38.91874,...",46,253,0,0,9,247,10,48387.0,3.0,100,None,"74,75",CI,12,247,Agroval,SMT,Cítricos,False

In [2]:
main_gdf

,geometry,provincia,municipio,agregado,zona,poligono,parcela,recinto,dn_surface,pendiente_media,coef_regadio,admisibilidad,incidencias,uso_sigpac,region,altitud,field,client,crop,operating
0,"POLYGON ((-0.65486 38.91992, -0.65491 38.92001...",46,176,0,0,14,1,1,91187.0,5.1,100,None,"74,75",CI,12,255,Agroval,SMT,Cítricos,False
0,"POLYGON ((-0.65367 38.92137, -0.65372 38.92139...",46,176,0,0,14,1,11,3307.0,4.8,100,None,"220,74",CI,6,253,Agroval,SMT,Cítricos,False
0,"POLYGON ((-0.65277 38.91852, -0.65283 38.91859...",46,176,0,0,14,1,4,320.0,10.7,100,None,"199,75",FY,12,239,Agroval,SMT,Cítricos,False
0,"POLYGON ((-0.65658 38.9197, -0.65664 38.91973,...",46,253,0,0,9,247,14,23355.0,4.0,100,None,"74,75",CI,12,251,Agroval,SMT,Cítricos,False
0,"POLYGON ((-0.66002 38.91788, -0.6609 38.91874,...",46,253,0,0,9,247,10,48387.0,3.0,100,None,"74,75",CI,12,247,Agroval,SMT,Cítricos,False

In [ ]:
import mongo_api as mapi
mapi.upload_plotlist_from_dataframe(main_gdf, True)

🗑️ Deleted 5 plots
🔄 Converting to EPSG:4326
✅ Valid plots found: 5
	 ['Agroval']
⚠️ Plots with no field found: 0
	 set()
🟡 Duplicates skipped: 0
📊 Successfully inserted 5 plots